name: Deploy contactflow

on:
  push:
    branches:
      - main

jobs:
  deploy_dev_to_qa:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed to authenticate with GitHub Packages
      contents: read # Needed to read the contents of the repository
    environment:
      name: dev_to_qa
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Checkout the code in the repository

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Node.js version to use

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::750344256621:role/CII-GitHub-Account-IAM-Role
          role-duration-seconds: 900 # optional, defaults to 3600 seconds
          aws-region: us-east-1 # use your region here.
   
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Load .env file
        run: |
          echo "Loading .env file"
          cat .env | while read line; do
            if [[ ! -z "$line" ]]; then
              echo "$line" >> $GITHUB_ENV
            fi
          done

      - name: Print environment variables
        run: |
          echo "DEV_INSTANCEARN: ${{ env.DEV_INSTANCEARN }}"
          echo "QA_INSTANCEARN: ${{ env.QA_INSTANCEARN }}"
          echo "FLOWNAME: ${{ env.FLOWNAME }}"
          echo "CONTACTFLOWTYPE: ${{ env.CONTACTFLOWTYPE }}"
          echo "SOURCE_REGION: ${{ env.DEV_REGION }}"
          echo "TARGET_REGION: ${{ env.QA_REGION }}"
          echo "RETRY_ATTEMPTS: ${{ env.RETRY_ATTEMPTS }}"

      - name: Run script
        run: |
          cd src
          node deployContactFlow.js
        env:
          SOURCE_INSTANCEARN: ${{ env.DEV_INSTANCEARN }}
          TRAGET_INSTANCEARN: ${{ env.QA_INSTANCEARN }}
          FLOWNAME: ${{ env.FLOWNAME }}
          CONTACTFLOWTYPE: ${{ env.CONTACTFLOWTYPE }}
          SOURCE_REGION: ${{ env.DEV_REGION }}
          TARGET_REGION: ${{ env.QA_REGION }}
          RETRY_ATTEMPTS: ${{ env.RETRY_ATTEMPTS }}

      - name: List files in src directory
        run: ls -l ${{ github.workspace }}/src

      - name: Upload output
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: ${{ github.workspace }}/src/*.json

  # deploy_qa_to_uat:
  #   needs: deploy_dev_to_qa
  #   runs-on: ubuntu-latest
  #   permissions:
  #     id-token: write # Needed to authenticate with GitHub Packages
  #     contents: read # Needed to read the contents of the repository
  #   environment:
  #     name: qa_to_uat
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2 # Checkout the code in the repository

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 18 # Node.js version to use

  #     - name: configure aws credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         role-to-assume: arn:aws:iam::750344256621:role/CII-GitHub-Account-IAM-Role
  #         role-duration-seconds: 900 # optional, defaults to 3600 seconds
  #         aws-region: us-east-1 # use your region here.
   
  #     - name: Install AWS CLI # Install AWS CLI
  #       run: |
  #         curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  #         unzip awscliv2.zip
  #         sudo ./aws/install --update

  #     - name: Load .env file
  #       run: |
  #         echo "Loading .env file"
  #         cat .env | while read line; do
  #           if [[ ! -z "$line" ]]; then
  #             echo "$line" >> $GITHUB_ENV
  #           fi
  #         done

  #     - name: Print environment variables
  #       run: |
  #         echo "DEV_INSTANCEARN: ${{ env.QA_INSTANCEARN }}"
  #         echo "QA_INSTANCEARN: ${{ env.UAT_INSTANCEARN }}"
  #         echo "FLOWNAME: ${{ env.FLOWNAME }}"
  #         echo "CONTACTFLOWTYPE: ${{ env.CONTACTFLOWTYPE }}"
  #         echo "REGION: ${{ env.REGION }}"
  #         echo "RETRY_ATTEMPTS: ${{ env.RETRY_ATTEMPTS }}"

  #     - name: Run script
  #       run: |
  #         cd src
  #         node deployContactFlow.js
  #       env:
  #         SOURCE_INSTANCEARN: ${{ env.QA_INSTANCEARN }}
  #         TRAGET_INSTANCEARN: ${{ env.UAT_INSTANCEARN }}
  #         FLOWNAME: ${{ env.FLOWNAME }}
  #         CONTACTFLOWTYPE: ${{ env.CONTACTFLOWTYPE }}
  #         REGION: ${{ env.REGION }}
  #         RETRY_ATTEMPTS: ${{ env.RETRY_ATTEMPTS }}

  #     - name: List files in src directory
  #       run: ls -l ${{ github.workspace }}/src

  #     - name: Upload output
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: output
  #         path: ${{ github.workspace }}/src/*.json
